### PR TITLE
WIP: Implement and enforce code style consistency

### PR DESCRIPTION
**Pull request by kdmccormick**
Fixing #49

### CODE REVIEW

**Comment by austintrose** [comment]
One useful thing I have at work is a `.git/hooks/pre-commit` file with the content:

```
# run some pep8 stuff
touched_python_files=`git diff --cached --diff-filter=ACMRT --name-only |egrep '\.py$' || true`
echo $touched_python_files
if [ -n "$touched_python_files" ]; then
    # If any Python files were modified, check the differences for valid pep8.
    exec git diff --cached $touched_python_files | flake8 --diff
fi
```

If that's there, then every time you try to make a commit, it runs `flake8` on the diff you're committing, and fails if there are any violations. You need to make sure you've done `pip install flake8` from wherever you're typing your git commands, though.

**Comment by kdmccormick** [comment]
@austintrose Thanks for the tip! We're doing pylint and pep8 on Travis. However, it might be annoying if every commit required style to pass (I tend to commit a lot while developing :P)

**Comment by kdmccormick** [comment]
@austintrose I'll put it in the developer guide in case anyone wants to do that.

**Comment by kdmccormick** [comment]
Closed in favor of #83

**Pull request closed without merging**
